### ISSUE TITLE
被踢不重连的问题貌似找到了

### ISSUE THREAD

**Issue by jsenetkx** [fanck0605/nanopi-r2s#15]
@fanck0605 
/etc/config/network里pppoe配置多了个option keepalive '0'

删掉保存   重启接口即可   两台机器(r2s n1)实测两天正常了    以前每天凌晨2点断开就连不上
这样做就是每次修改wan设置  还要改下network这个文件  lua修改会自动加上这一条

查了下lua文件 /usr/lib/lua/luci/model/cbi/admin_network/proto_pppoe.lua
function keepalive_interval.write(self, section, value)
	local f = tonumber(keepalive_failure:formvalue(section)) or 0
	local i = tonumber(value) or 5
	if i < 1 then i = 1 end
	if f > 0 then
		m:set(section, "keepalive", "%d %d" %{ f, i })
	else
		m:set(section, "keepalive", "0")
	end
end
else这里去掉   lua修改就不会加上了

**Comment by fanck0605** [comment]
@jsenetkx 我也不太清楚这个。
但这个只是个 luci 配置用的脚本，应该和掉线无关。

然后这个项目维护不太动了，看看 [openwrt-nanopi-r2s](https://github.com/fanck0605/openwrt-nanopi-r2s) 吧，

**Comment by jsenetkx** [comment]
我意思是 /etc/config/network里的option keepalive '0'是我这电信踢下线不自动重连的原因 原版openwrtluci里keepalive默认0的话是不会加到 /etc/config/network里的
实测几天了  删掉这句就能自动重连了  

不过你这项目也放弃了    溜了溜了
